### ISSUE TITLE
hehe first issue

### ISSUE THREAD

**Issue by AndreySolodovnikov** [Cow-berry/Notes#5]
Линейный анализ -> линейная алгебра =)

**Comment by AndreySolodovnikov** [comment]
upd : wops, not first

**Comment by Cow-berry** [comment]
updupd : it's first, but there were 4 firsts before

> upd : wops, not first

**Comment by Cow-berry** [comment]
![image](https://user-images.githubusercontent.com/13920859/98964975-81ae6700-251a-11eb-9a8c-635869cfa4d3.png)
Засим ишью закрывается
